dbfilename redis_cache.rdb
dir /home/user/cay_xanh_do_thi/be/v16-bench/config/pids
pidfile /home/user/cay_xanh_do_thi/be/v16-bench/config/pids/redis_cache.pid
bind 127.0.0.1
port 13010
maxmemory 389mb
maxmemory-policy allkeys-lru
appendonly no

save ""


aclfile /home/user/cay_xanh_do_thi/be/v16-bench/config/redis_cache.acl
