dbfilename redis_queue.rdb
dir /home/user/cay_xanh_do_thi/be/v16-bench/config/pids
pidfile /home/user/cay_xanh_do_thi/be/v16-bench/config/pids/redis_queue.pid
bind 127.0.0.1
port 11010

aclfile /home/user/cay_xanh_do_thi/be/v16-bench/config/redis_queue.acl
